-- MySQL Script generated by MySQL Workbench
-- Wed Jan 22 13:25:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema DBCreationAndSQLStatements
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBCreationAndSQLStatements
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBCreationAndSQLStatements` DEFAULT CHARACTER SET utf8mb4 ;
USE `DBCreationAndSQLStatements` ;

-- -----------------------------------------------------
-- Table `DBCreationAndSQLStatements`.`avatars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBCreationAndSQLStatements`.`avatars` (
  `# id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  `appearance` TEXT NULL DEFAULT NULL,
  `level` INT NULL DEFAULT NULL,
  PRIMARY KEY (`# id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `DBCreationAndSQLStatements`.`confrontations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBCreationAndSQLStatements`.`confrontations` (
  `# id` INT NOT NULL,
  `match_id` INT NOT NULL,
  `avatar1_id` INT NOT NULL,
  `avatar2_id` INT NULL DEFAULT NULL,
  `result` INT NULL DEFAULT NULL,
  PRIMARY KEY (`# id`))
ENGINE = InnoDB -- Cambiado de FEDERATED a InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `DBCreationAndSQLStatements`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBCreationAndSQLStatements`.`games` (
  `# id` INT NOT NULL,
  `code` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `rules` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`# id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `DBCreationAndSQLStatements`.`match_participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBCreationAndSQLStatements`.`match_participants` (
  `match_id` INT NOT NULL,
  `avatar_id` INT NOT NULL,
  PRIMARY KEY (`match_id`, `avatar_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `DBCreationAndSQLStatements`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBCreationAndSQLStatements`.`matches` (
  `# id` INT NOT NULL,
  `game_id` INT NOT NULL,
  `name` TEXT NOT NULL,
  `password` TEXT NULL DEFAULT NULL,
  `created_at` DATE NULL DEFAULT NULL,
  `status` TEXT NOT NULL,
  `creator_avatar_id` INT NOT NULL,
  PRIMARY KEY (`# id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `DBCreationAndSQLStatements`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBCreationAndSQLStatements`.`users` (
  `# id` INT NOT NULL,
  `name` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `nick` TEXT NOT NULL,
  `login` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `birthdate` DATE NOT NULL,
  PRIMARY KEY (`# id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
